### ISSUE TITLE
Search fields in relations with 'or' operator

### ISSUE THREAD

**Issue by manuelantoncalvo** [elfif/metasearch_l5#4]
The parameter q[name_or_contacts.name_equals]=test generates the following query, which is incorrect: 

`select * from vendors where (name= ‘test’ and exists (select * from contacts where (vendors.id=contacts.vendor_id or (name = ‘test’)); .`

In that query, the conjunction operator is and, but should be or.

**Comment by Kryptonien** [comment]
Thank you for the pull request. It is now merged into the repository.
